name: Test build
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dist
          path: dist/
          retention-days: 30
